### ISSUE TITLE
[22-01-14] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#104]
- [ ] 정보처리기사 실기 개념 19강

- [ ] 정보처리기사 실기 SQL 응용 기출문제 풀기  

- [ ] IOS 앱개발 CoreML 개와 강아지 분류기 (1/3)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 2장 49~60번까지 틀린문제 오답정리

> **백준 알고리즘 이제까지 못한부분이나, 공부해야할 부분 예습,복습하세요.**

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260/222623651320
