### ISSUE TITLE
[22-01-18] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#107]
- [ ] 정보처리기사 실기 개념 20강

- [ ] 정보처리기사 실기 문제풀이 8강 

- [ ] IOS 앱개발 CoreML 개와 강아지 분류기 (1/3)

- [ ] 스프링MVC 웹 서버, 웹 어플리케이션 서버 ~ HTML,HTTP,API,CSR,SSR

- [ ] 정보처리기사 필기 문제풀이 3장 1~12번까지 틀린문제 오답정리

- [ ] 백준 알고리즘 자료구조1(참고) 후위표기식2~접미사 배열까지
https://code.plus/course/41
