### ISSUE TITLE
[21-01-18] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#108]
- [ ] 정보처리기사 실기 개념 20강

- [ ] 정보처리기사 실기 문제풀이 8강 

- [ ] 자바스크립트 - 16~21강

- [ ] 자바스크립트 공부한거 블로그 쓰고 댓글

- [ ] 정보처리기사 필기 문제풀이 3장 1~12번까지 틀린문제 오답정리

- [ ] 백준 알고리즘 자료구조1(참고) 후위표기식2~접미사 배열까지
https://code.plus/course/41

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222624308045
