### ISSUE TITLE
[21-01-19] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#112]
- [ ] 정보처리기사 실기 개념 21강

- [ ] 정보처리기사 실기 문제풀이 9강 

- [ ] 스프링입문 -  디자인패턴

- [ ] 자바 공부한거 블로그 쓰고 댓글

- [ ] 정보처리기사 필기 문제풀이 3장 13~36번까지 틀린문제 오답정리

> 이번주 알고리즘 공부 [자료구조1](https://github.com/gudals-kim/Nobrain-study/tree/master/13_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%201)

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222626263598
