### ISSUE TITLE
[21-01-19] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#114]
- [ ] 정보처리기사 실기 개념 21강

- [ ] 정보처리기사 실기 문제풀이 9강 

- [ ] 스위프트 CoreML 개와 강아지 분류기 (2/3)

- [ ] 스위프트 공부한거 블로그 쓰고 댓글

- [ ] 정보처리기사 필기 문제풀이 3장 13~36번까지 틀린문제 오답정리

> 이번주 알고리즘 공부 [자료구조1](https://github.com/gudals-kim/Nobrain-study/tree/master/13_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%201)

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260/222630544089
