### ISSUE TITLE
[21-01-20] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#116]
- [ ] 정보처리기사 실기 개념 22강

- [ ] 정보처리기사 실기 소프트웨어 개발 보안 구축 기출문제 풀기

- [ ] 자바 스크립트 - 30~05

- [ ] 자바스크립트 공부한거 블로그 쓰고 댓글

- [ ] 정보처리기사 필기 문제풀이 3장 37~48번까지 틀린문제 오답정리

> 이번주 알고리즘 공부 [자료구조1](https://github.com/gudals-kim/Nobrain-study/tree/master/13_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%201)
