### ISSUE TITLE
[22-01-20] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#117]
- [x] 정보처리기사 실기 개념 22강

- [x] 정보처리기사 실기 소프트웨어 개발 보안 구축 기출문제 풀기

- [x] 스프링 입문 - 스프링 부트 시작하기

- [x] 디자인패턴 -  프록시 패턴

- [x] 스프링or 자바 공부한거 블로그에 쓰고 댓글

- [x] 정보처리기사 필기 문제풀이 3장 37~48번까지 틀린문제 오답정리

> 이번주 알고리즘 공부 [자료구조1](https://github.com/gudals-kim/Nobrain-study/tree/master/13_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%201)
