### ISSUE TITLE
[22-01-20] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#118]
- [ ] 정보처리기사 실기 개념 22강

- [ ] 정보처리기사 실기 소프트웨어 개발 보안 구축 기출문제 풀기

- [ ] httpServletRequest - 기본사용법 ~ Http요청데이터 POST HTML Form

- [ ] MVC 공부한거 블로그 쓰고 댓글

- [ ] 정보처리기사 필기 문제풀이 3장 37~48번까지 틀린문제 오답정리

> 이번주 알고리즘 공부 [자료구조1](https://github.com/gudals-kim/Nobrain-study/tree/master/13_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%201)

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222627905695
