### ISSUE TITLE
[22-01-21] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#122]
- [ ] 정보처리기사 실기 개념 23강

- [ ] 스위프트 개와 강아지 분류기 3/3

- [ ] 스위프트 공부한거 블로그에 쓰고 댓글

- [ ] 정보처리기사 필기 문제풀이 3장 49~60번까지 틀린문제 오답정리

> 이번주 알고리즘 공부 [자료구조1](https://github.com/gudals-kim/Nobrain-study/tree/master/13_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%201)
