### ISSUE TITLE
[22-01-24] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#125]
- [ ] 정보처리기사 실기 개념 24강

- [ ]  자바스크립트 1~3

- [ ] 자바스크립트 공부한거 복습하고 블로그에 쓴 후 댓글

- [ ] 정보처리기사 필기 문제풀이 4장 1~12번까지 틀린문제 오답정리

> 이번주 알고리즘 공부 설 전까지 모두 업로드 해주시길 바랍니다. [자료구조1](https://github.com/gudals-kim/Nobrain-study/tree/master/13_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%201)

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222630543299
