### ISSUE TITLE
[22-01-24] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#128]
- [ ] 정보처리기사 실기 개념 24강

- [ ] 스프링 입문 - 스프링 기능 활용 (1/2)

- [ ] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [ ] 정보처리기사 필기 문제풀이 4장 1~12번까지 틀린문제 오답정리

> 이번주 알고리즘 공부 설 전까지 모두 업로드 해주시길 바랍니다. [자료구조1](https://github.com/gudals-kim/Nobrain-study/tree/master/13_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%201)

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222632364747
