### ISSUE TITLE
[22-01-27] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#135]
- [ ] 정보처리기사 실기 개념 26강

- [ ] 스위프트 복습

- [ ] 스위프트 복습후 블로그에 정리해서 올리고 댓글

- [ ] 정보처리기사 필기 문제풀이 4장 37~48번까지 틀린문제 오답정리

> 이번주 알고리즘 공부 설 전까지 모두 업로드 해주시길 바랍니다. [자료구조1](https://github.com/gudals-kim/Nobrain-study/tree/master/13_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0%201)

**Comment by park121234** [comment]
https://blog.naver.com/PostView.naver?blogId=rhkdgus5260&Redirect=View&logNo=222633078085&categoryNo=25&isAfterWrite=true&isMrblogPost=false&isHappyBeanLeverage=true&contentLength=7953
