### ISSUE TITLE
[22-02-09] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#147]
- [ ] 정보처리기사 실기 개념 29강

- [ ] 스프링 MVC - 서블릿

- [ ] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [ ] 정보처리기사 필기 모의고사 1회 풀기

- [ ] 알고리즘 공부 -  자료구조(링크드리스트)
