### ISSUE TITLE
[22-02-09] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#148]
- [ ] 스프링 MVC -  단순하고 실용적인 컨트롤러 - v4 ~ 정리

- [ ] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [ ] 정보처리기사 필기 모의고사 1회 풀기

- [ ] 정보처리기사 필기 모의고사 1회 틀린문제 오답하기

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222643507185
