### ISSUE TITLE
[22-02-29] 이정현 To-do 

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#149]
- [ ] 정보처리기사 실기 개념 28강

- [ ] 리엑트 7장- 11~16강

- [ ] 리엑트 공부한거 복습하고 블로그에 쓴 후 댓글

- [ ] 정보처리기사 필기 모의고사 1회 풀기

- [ ] 정보처리기사 필기 모의고사 1회 오답풀이

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222643513236
