### ISSUE TITLE
[22-02-10] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#158]
- [x] 정보처리기사 실기 개념 29강

- [x] 정보처리기사 실기 문제풀이 10강

- [x] 9. 스프링 MVC 전체 구조 ~ 스프링 MVC - 시작하기

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 필기 모의고사 2회 풀기

- [x] 정보처리기사 필기 모의고사 2회 오답풀이

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222646802705
