### ISSUE TITLE
[22-02-11] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#160]
- [x] 정보처리기사 실기 문제풀이 11강

- [x] 리엑트 - 8장 00강~07강

- [x] 리엑트 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 필기 모의고사 3회 풀기

- [ ] 정보처리기사 필기 모의고사 3회 오답풀이

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337
