### ISSUE TITLE
[22-02-14] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#162]
- [x] 정보처리기사 실기 프로그래밍 언어 활용 문제 풀기

- [x] 스프링 MVC - MVC 프레임 워크 만들기 (1/2)

- [ ] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 필기 모의고사 4회 풀기

알고리즘 공부 -  자료구조(링크드리스트)
