### ISSUE TITLE
[22-02-14] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#163]
- [x] 정보처리기사 실기 프로그래밍 언어 활용 문제 풀기

- [x] 스프링 MVC 11. 프로젝트 생성 ~ 요청 매핑 - API 예시

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 필기 모의고사 4회 풀기

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222650005310
