### ISSUE TITLE
[22-02-14] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#164]
- [x] 정보처리기사 실기 프로그래밍 언어 활용 문제 풀기

- [x] 리엑트 -  8장 {08강 ~ 11강}

- [x] 리엑트 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 필기 모의고사 4회 풀기

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337
