### ISSUE TITLE
[22-02-14] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#165]
- [ ] 정보처리기사 실기 프로그래밍 언어 활용 문제 풀기

- [x] IOS 앱 - 원피스 현상금앱(2/2)

- [x] 스위프트 공부한거 복습하고 블로그에 쓴 후 댓글

- [ ] 정보처리기사 필기 모의고사 4회(21년 필기 1회)까지 풀기
