### ISSUE TITLE
[22-02-15] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#166]
- [x] 정보처리기사 실기 개념 30강 듣기

- [x] 스프링 MVC - MVC프레임 워크 만들기 (2/2)

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 5회 풀기 

- [x] 정보처리기사 필기 모의고사 4회 오답
