### ISSUE TITLE
[22-02-15] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#167]
- [x] 정보처리기사 실기 개념 30강 듣기

- [x] 리엑트 - 8장 {12장 ~ 18강}

- [x] 리엑트 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 5회 풀기 

- [x] 정보처리기사 필기 모의고사 4회 오답
