### ISSUE TITLE
[22-02-15] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#168]
- [x] 정보처리기사 실기 개념 30강 듣기

- [x] spring MVC  HTTP 요청 - 기본, 헤더 조회 ~ HTTP 요청 파라미터 - @ModelAttribute

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 5회 풀기 

- [x] 정보처리기사 필기 모의고사 4회 오답

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222650127635
