### ISSUE TITLE
[22-02-16] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#170]
- [x] 정보처리기사 실기 개념 31강 듣기

- [x] 스프링 MVC -  복습

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 6회 풀기 

- [x] 정보처리기사 필기 모의고사 5회 오답
