### ISSUE TITLE
[22-02-16] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#171]
- [x] 정보처리기사 실기 개념 31강 듣기

- [x] 리엑트 프로젝트 계획서 작성하기

- [x] 정보처리기사 6회 풀기 

- [x] 정보처리기사 필기 모의고사 5회 오답
