### ISSUE TITLE
[22-02-16] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#172]
- [x] 정보처리기사 실기 개념 31강 듣기

- [x] 13. HTTP 요청 메시지 - 단순 텍스트 ~ HTTP 응답 - HTTP, API, 메시지 바디에 직접 입력

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 6회 풀기 

- [x] 정보처리기사 필기 모의고사 5회 오답

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222653338843
