### ISSUE TITLE
[22-02-17] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#173]
- [x] 애듀윌 정보처리기사 실기 문제풀이 12강

- [x] 스프링 MVC -  복습

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 애듀윌 정보처리기사 필기 CBT 풀기

- [x] 정보처리기사 필기 모의고사 6회 오답

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222650395246
