### ISSUE TITLE
[22-02-17] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#174]
- [x] 애듀윌 정보처리기사 실기 문제풀이 12강

- [x] 개인 프로젝트 -  <1> Oven에 페이지 스타일 완성하기

- [x] 애듀윌 정보처리기사 필기 CBT 풀기

- [x] 정보처리기사 필기 모의고사 6회 오답
