### ISSUE TITLE
[22-02-17] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#175]
- [x] 애듀윌 정보처리기사 실기 문제풀이 12강

- [x] 스프링MVC -  14. HTTP 메시지 컨버터 ~ 정리

- [x] 스프링 MVC 공부한거 블로그에 쓰면서 복습하고 댓글 

- [x] 애듀윌 정보처리기사 필기 CBT 풀기

- [x] 정보처리기사 필기 모의고사 6회 오답

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222653394596
