### ISSUE TITLE
[22-02-21] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#176]
- [x] 애듀윌 정보처리기사 필기 복습 1강

- [x] 스프링 MVC -  스프링 MVC 구조이해

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222653793224
