### ISSUE TITLE
[22-02-21] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#177]
- [x] 애듀윌 정보처리기사 필기 복습 1강

- [x] 스프링 MVC -   프로젝트 생성 ~ 상품 서비스 HTML

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222659481047
