### ISSUE TITLE
[22-02-22] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#181]
- [x] 애듀윌 정보처리기사 필기 복습 2강

- [x] 스프링 MVC -  상품목록 - 타임리프 ~ 상품 등록 처리 - @ModelAttribute

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222659481047
