### ISSUE TITLE
[22-02-22] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#182]
- [x] 애듀윌 정보처리기사 필기 복습 1강

- [x] 애듀윌 정보처리기사 필기 복습 2강

- [x] IOS - 현상금 앱 업그레이드 버전(1/2)

- [x] 스위프트 공부한거 복습하고 블로그에 쓴 후 댓글

**Comment by ghost** [comment]
https://blog.naver.com/rhkdgus5260/222655435081
