### ISSUE TITLE
[22-02-23] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#185]
- [x] 애듀윌 정보처리기사 필기 복습 3강

- [x] IOS -  현상금 앱 업그레이드 버전(2/2)

- [x] 스위프트 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] 정보처리기사 필기 CBT 오답

**Comment by ghost** [comment]
https://blog.naver.com/rhkdgus5260/222656792989
