### ISSUE TITLE
[22-02-24] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#187]
- [x] 애듀윌 정보처리기사 필기 복습 4강

- [ ] 스프링 MVC - 웹 페이지만들기 (1/3)

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222656102592
