### ISSUE TITLE
[22-02-24] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#190]
- [x] 애듀윌 정보처리기사 필기 복습 4강

- [x] IOS -  애플뮤직st 음악앱(1/2)

- [x] 스위프트 공부한거 복습하고 블로그에 쓴 후 댓글
