### ISSUE TITLE
[22-02-28] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#195]
- [x] 정보처리기사 필기 20년 1/2회 통합 풀기

- [ ] 스프링 MVC -  웹페이지 만들기(3/3)

- [x] 스프링 공부한거 복습하고 블로그에 쓴 후 댓글

- [x] HTTP 개념(1/5)

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222657065613
