### ISSUE TITLE
[22-02-28] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#198]
- [x] 정보처리기사 필기 1/2회 통합 풀기

- [x] IOS 개발 - todo리스트 앱 

- [x] 스위프트 공부한거 블로그에 쓰면서 복습 올리고 댓글

**Comment by ghost** [comment]
https://blog.naver.com/rhkdgus5260
