### ISSUE TITLE
[22-03-01] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#199]
- [x] 정보처리기사 필기 20년 3회 풀기

- [x] 정보처리기사 필기 20년 4회 풀기

- [x] 정보처리기사 필기 20년 1/2회 통합 오답 풀이

- [x] 공부한거 복습하고 블로그에 쓴 후 댓글

- [ ] HTTP 개념(2/5)

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222660578327
