### ISSUE TITLE
[22-03-01] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#200]
- [x] 정보처리기사 필기 20년 3회 풀기

- [x] 정보처리기사 필기 20년 4회 풀기

- [x] 정보처리기사 필기 20년 1/2회 통합 오답 풀이

- [ ] 개인 프로젝트 진행

- [ ] HTTP 개념(2/5)
