### ISSUE TITLE
[22-03-01] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#202]
- [x] 정보처리기사 필기 20년 3회 풀기

- [x] 정보처리기사 필기 20년 4회 풀기

- [x] 정보처리기사 필기 20년 1/2회 통합 오답 풀이

- [ ] 공부한거 복습하고 블로그에 쓴 후 댓글

- [ ] IOS - 넷플릭스 st 영상앱 (1/2)
