### ISSUE TITLE
[22-03-02] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#206]
- [x] 정보처리기사 필기 20년 3회 오답풀이

- [x] 정보처리기사 필기 20년 4회 오답풀이

- [x] 정보처리기사 필기 21년 1회 풀기

- [ ] 공부한거 복습하고 블로그에 쓴 후 댓글

- [ ] HTTP 개념(3/5)
