### ISSUE TITLE
[22-03-14] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#220]
- [x] [HTTP개념] - HTTP메서드 활용 ~ HTTP 상태코드 (3/5)

- [ ] [Spring]  - 타임리프 기본기능 (2/2)

- [ ] [JPA] - 엔티티 매핑 

- [x] [캡스톤 디자인 ] - Django 프레임워크 

- [x] [캡스톤 디자인] - 크롤링 기능 구현 

- [ ] [정보처리기사] - 실기 계획 짜기
