### ISSUE TITLE
[22-04-04] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#226]
- [x] [정보처리기사] 제 1장 요구사항 확인 (1)

- [x] [정보처리기사] 제 1장 요구사항 확인 (2) 

- [x] [캡스톤디자인] 크롤링 개발 및 추천알고리즘 개발
