### ISSUE TITLE
[22-04-05] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#229]
- [x] [정보처리기사] ```문제풀기``` 2과목 60문제 풀기

- [x] [정보처리기사] ```문제풀기``` 3과목 60문제 풀기

- [x] [정보처리기사] ```문제풀기``` 2과목/3과목 오답정리 

- [x] [캡스톤디자인] 냉장고 팝업창 및 영역별 선택시 이동 구현
