### ISSUE TITLE
[22-04-05] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#230]
- [x] [정보처리기사] 2, 3과목 60문제 풀기 + 오답정리

- [x] [HTML] 레이아웃 만들기 1 : 호환성 좋은 float

- [x] [HTML] 레이아웃 만들기 2 : 귀찮은 inline-block
