### ISSUE TITLE
[22-04-06] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#233]
- [x] [정보처리기사] ```문제풀기``` 4과목 60문제 풀기

- [x] [정보처리기사] ```문제풀기``` 5과목 60문제 풀기

- [x] [정보처리기사] ```문제풀기``` 4과목/5과목 오답정리 

- [ ] [캡스톤디자인] 냉장고 팝업창 및 영역별 선택시 이동 구현
