### ISSUE TITLE
[22-04-06] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#234]
- [x] [정보처리기사] ```문제풀기``` 4과목 60문제 풀기

- [x] [정보처리기사] ```문제풀기``` 5과목 60문제 풀기

- [x] [정보처리기사] ```문제풀기``` 4과목/5과목 오답정리 

- [x] [HTML] 레이아웃 만들기 숙제 : Blog 글목록 만들기

- [x] [HTML] 셀렉터를 이용해 CSS 코드 양 줄이기

- [x] [HTML] 배경 이쁘게 넣는 스킬들 & margin collapse

- [x] [HTML] position과 좌표 레이아웃 만들기

- [x] [HTML] position 숙제 & 반응형 width & box-sizing
