### ISSUE TITLE
[22-04-07] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#237]
- [x] [정보처리기사] ```모의고사``` 2020년 1/2회 통합 풀기

- [x] [정보처리기사] ```모의고사``` 2020년 3회 풀기

- [x] [정보처리기사] ```문제풀기``` 1/2회 , 3회 오답정리 

- [x] [캡스톤디자인] 냉장고 팝업창 및 영역별 선택시 이동 구현
