### ISSUE TITLE
[22-04-11] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#241]
- [x] [정보처리기사] ```모의고사``` 2022년 제1회 필기시험

- [x] [정보처리기사] ```모의고사``` 2022 1강 에듀윌 CBT모의고사

- [x] [정보처리기사] ```오답정리``` 2022년 제1회 필기시험, 2022 1강 에듀윌 CBT모의고사

- [ ] [캡스톤디자인] (2-4) 선택된 리스트 (확인) 이동
