### ISSUE TITLE
[22-04-11] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#244]
- [x] [정보처리기사] ```실기 문제 풀기``` 데이터 입출력 구현

- [x] [정보처리기사] ```실기 문제 풀이``` 데이터 입출력 구현

- [x] [캡스톤 디자인] 추천알고리즘 개발

- [x] [캡스톤 디자인] DB 완성
