### ISSUE TITLE
[22-04-12] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#246]
- [x] [정보처리기사] ```모의고사``` 2021년 제2회 필기시험

- [x] [정보처리기사] ```모의고사``` 2021년 제3회 필기시험

- [x] [정보처리기사] ```오답정리``` 2021년 제2회 필기시험, 제3회 필기시험

- [x] [캡스톤디자인] (2-4) 선택된 리스트 (확인) 이동
