### ISSUE TITLE
[22-04-12] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#248]
- [x] [정보처리기사] ```실기 개념 정리``` 제3장 통합 구현(1)

- [x] [정보처리기사] ```실기 개념 정리``` 제3장 통합 구현(2)

- [x] [캡스톤 디자인] 추천알고리즘 개발

- [x] [캡스톤 디자인] DB 완성
