### ISSUE TITLE
[22-04-14] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#256]
- [x] [정보처리기사] ```기본 개념 듣기 ``` 제4장 서버프로그램 

- [x] [정보처리기사] ```문제 풀기``` 제4장 서버프로그램

- [x] [정보처리기사] ```문제 풀이 듣기``` 제4장 서버프로그램

- [x] [캡스톤 디자인] 추천알고리즘 개발

- [x] [캡스톤 디자인] DB 완성
