### ISSUE TITLE
[22-04-21] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#259]
- [x] [정보처리기사] ```실기 이론 듣기``` 제 8장 SQL응용(3)

- [x] [정보처리기사] ```실기 문제 풀기``` 제 8장 SQL응용

- [x] [정보처리기사] ```실기 문제 풀이 듣기``` 제 8장 SQL응용
