### ISSUE TITLE
[22-06-09] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#261]
- [x] [HTML] Font Awesome 아이콘 넣기 

- [x] [HTML] Transition 속성으로 CSS 애니메이션 구현하기

- [x] [HTML] Transition 숙제 : 상품진열 레이아웃과 애니메이션

- [x] [HTML] Portfolio 실습 1 : Landing Page

- [ ] [정보처리기사] 실기 대비 계획 짜기
