### ISSUE TITLE
[22-06-22] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#269]
- [x] [정보처리기사] ```필기 모의고사``` 2021년 1회 풀기

- [x] [정보처리기사] ```필기 모의고사``` 2021년 1회 오답정리

- [x] [정보처리기사] ```필기 모의고사``` 2021년 2회 풀기

- [x] [정보처리기사] ```필기 모의고사``` 2021년 2회 오답정리
