### ISSUE TITLE
[22-06-22] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#270]
- [x] [스프링 MVC] 타임리프 기본기능

- [x] [자료구조이론] 알고리즘 복잡도 표현 방법

- [x] [프로젝트] OCR과 서버 데이터 전처리
