### ISSUE TITLE
[22-06-22] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#271]
- [x] [정보처리기사] ```2020년 실기``` 1회 풀기

- [x] [정보처리기사] ```2020년 실기``` 1회 오답정리

- [x] [정보처리기사] ```실기모의고사``` 1회 풀기

- [x] [코딩테스트] ```String 문자열``` 공부하기
