### ISSUE TITLE
[22-06-23] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#275]
- [x] [정보처리기사] ```2020년 실기``` 2회 풀기

- [x] [정보처리기사] ```2020년 실기``` 2회 오답정리

- [x] [정보처리기사] ```실기모의고사``` 2회 풀기

- [x] [코딩테스트] ```Arrays 다차원배열``` 공부하기
