### ISSUE TITLE
[22-06-24] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#276]
- [x] [정보처리기사] ```2020년 실기``` 3회 풀기

- [x] [정보처리기사] ```2020년 실기``` 3회 오답정리

- [x] [정보처리기사] ```실기모의고사``` 3회 풀기

- [ ] [코딩테스트] ```Two pointers, Sliding window``` 공부하기
