### ISSUE TITLE
[22-06-24] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#277]
- [x] [정보처리기사] ```필기 모의고사``` 2022년 1회 풀기

- [ ] [정보처리기사] ```필기 모의고사``` 2022년 1회 오답정리

- [x] [정보처리기사] ```필기 모의고사``` 2022년 2회 풀기

- [ ] [정보처리기사] ```필기 모의고사``` 2022년 2회 오답정리
