### ISSUE TITLE
[22-06-30] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#285]
- [x] [정보처리기사] ```2021년 실기``` 2회 풀기

- [x] [정보처리기사] ```2021년 실기``` 2회 오답정리

- [x] [정보처리기사] ```실기모의고사``` 5회 풀기

- [ ] [코딩테스트] ```Stack, Queue``` 공부하기
