### ISSUE TITLE
[22-07-04] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#288]
- [ ] [정보처리기사] ```2021년 실기``` 3회 풀기

- [ ] [정보처리기사] ```2021년 실기``` 3회 오답정리

- [ ] [정보처리기사] ```실기모의고사``` 6회 풀기

- [ ] [코딩테스트] ```Sorting and Searching``` 공부하기
