### ISSUE TITLE
[22-07-05] 박광현 To-do 

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#290]
- [x] [정보처리기사] ```실기 기본이론``` 22강 듣기

- [x] [정보처리기사] ```실기 기본이론``` 23강 듣기

- [x] [정보처리기사] ```실기 기본이론``` 24강 듣기

- [x] [정보처리기사] ```실기 기본이론``` 25강 듣기
