### ISSUE TITLE
[22-07-05] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#291]
- [ ] [정보처리기사] ```실기모의고사``` 7회 풀기

- [ ] [정보처리기사] ```실기모의고사``` 8회 풀기

- [ ] [코딩테스트] ``` Recursive, Tree, Graph``` 공부하기
