### ISSUE TITLE
[22-08-22] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#316]
- [ ] 쉽게 배우는 Sass 기초 1편 : 셋팅

- [ ] 쉽게 배우는 Sass 2편 : 핵심문법

- [ ] 쉽게 배우는 Sass 3편 : Mixin, use 등
