### ISSUE TITLE
[22-08-22] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#317]
- [x] [HTTP기본] HTTP 메서드 *복습

- [x] [MVC] 회원 관리 예제 - 백엔드 개발 *복습

- [x] [ORM] 영속성 관리 - 내부 동작 방식

- [ ] [코딩테스트] 자료구조(트리)
