### ISSUE TITLE
[21-12-20] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#54]
- [ ] 정보처리기사 실기 개념 9강

- [ ] 정보처리기사 실기 인터페이스 구현 문제풀기

- [ ] 스위프트 14강 네트워킹 (1)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260/222600575214
