### ISSUE TITLE
[21-12-20] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#55]
- [ ] 정보처리기사 실기 개념 9강

- [ ] 정보처리기사 실기 인터페이스 구현 문제풀기

- [ ] 자바 어드민페이지 프로젝트  7-2 ~ 8-1-03

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222600555404
