### ISSUE TITLE
[21-12-20] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#57]
- [ ] 정보처리기사 실기 개념 9강

- [ ] 정보처리기사 실기 문제풀이 3강

- [ ] 정보처리기사 인터페이스 구현 문제풀기

- [ ] 리엑트 4장 {04강 ~ 07강}

- [ ] 리엑트 공부한거 블로그에 포스팅 후 댓글
