### ISSUE TITLE
[22-01-03] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#58]
- [ ] 정보처리기사 실기 개념 10강

- [ ] 정보처리기사 서버프로그램/인터페이스 구현 문제풀기

- [ ] 15강 넷플릭스st 영상앱 (1/2)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

- [ ] 필기 문제풀이 1장 ~12번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 입출력과 사칙연산/if문/for문까지 풀고 문제코드 올리기
https://www.acmicpc.net/step (백준 알고리즘 문제)
