### ISSUE TITLE
[22-01-03] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#59]
- [ ] 정보처리기사 실기 개념 10강

- [ ] 자바 8-1-04 ~ 8-2-02강

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

- [ ] 필기 문제풀이 1장 ~12번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 입출력과 사칙연산/if문/for문까지 풀고 문제코드 올리기
https://www.acmicpc.net/step (백준 알고리즘 문제)

**Comment by gudals-kim** [comment]
https://www.inflearn.com/course/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EA%B0%95%EC%A2%8C

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222612133337
