### ISSUE TITLE
[22-01-03] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#60]
- [ ] 정보처리기사 실기 개념 10강

- [ ] 정보처리기사 실기 서버프로그램 문제풀기 

- [ ] 리엑트 5장 {00강 ~ 07강}

- [ ] 리엑트 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 ~12번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 입출력과 사칙연산/if문/for문까지 풀고 문제코드 올리기
https://www.acmicpc.net/step (백준 알고리즘 문제)

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222612111677
https://blog.naver.com/leel5337/222612226063
