### ISSUE TITLE
[22-01-03] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#61]
- [ ] 정보처리기사 실기 개념 10강

- [ ] 정보처리기사 실기 서버프로그램/인터페이스 구현 문제풀기 

- [ ] 코틀린 ch1 bmi 계산기 프로젝트

- [ ] 코틀린 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 ~12번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 입출력과 사칙연산/if문/for문까지 풀고 문제코드 올리기
https://www.acmicpc.net/step (백준 알고리즘 문제)

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222612218795
