### ISSUE TITLE
[22-01-04] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#64]
- [ ] 정보처리기사 실기 개념 11강

- [ ] 정보처리기사 실기 문제풀이 4강  

- [ ] 15강 넷플릭스st 영상앱 (2) 2/2

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 13~24번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 입출력과 while문/1차원배열/함수/문자열까지 풀고 문제코드 올리기
https://www.acmicpc.net/step (백준 알고리즘 문제)
