### ISSUE TITLE
[22-01-04] 이정현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#66]
- [ ] 정보처리기사 실기 개념 11강

- [ ] 정보처리기사 실기 문제풀이 4강  

- [ ] 자바스크립트 01~10

- [ ] 자바스크립트 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 13~24번까지 틀린문제 오답정리

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222613216449
