### ISSUE TITLE
[22-01-05] 이정형 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#68]
- [ ] 정보처리기사 실기 개념 12강

- [ ] 정보처리기사 실기  문제풀이 인터페이스 구현(5강) 듣기

- [ ] 자바스크립트  {11 ~ 15}

- [ ] 자바스크립트 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 25~36번까지 틀린문제 오답정리

**Comment by leel5337** [comment]
https://blog.naver.com/leel5337/222614165704
