### ISSUE TITLE
[22-01-05] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#69]
- [ ] 정보처리기사 실기 개념 12강

- [ ] 정보처리기사 실기  문제풀이 인터페이스 구현(5강) 듣기

- [ ] 스위프트 Firebase(1/3)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 25~36번까지 틀린문제 오답정리
