### ISSUE TITLE
[22-01-05] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#70]
- [ ] 정보처리기사 실기 개념 12강

- [ ] 정보처리기사 실기  문제풀이 인터페이스 구현(5강) 듣기

- [ ] 안드로이드 비밀다이어리 프로젝트

- [ ] 코틀린 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 25~36번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 입출력과 기본수학1/기본수학2까지 풀고 문제코드 올리기
https://www.acmicpc.net/step (백준 알고리즘 문제)

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222614611094
