### ISSUE TITLE
[22-01-06] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#73]
- [ ] 정보처리기사 실기 개념 13강

- [ ] 정보처리기사 실기  화면설계 문제풀기

- [ ]  api 과제 하기

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 37~48번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 입출력과 재귀/브루트포스 까지 풀고 문제코드 올리기
https://www.acmicpc.net/step (백준 알고리즘 문제)

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222614870344
