### ISSUE TITLE
[22-01-07] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#80]
- [ ] 정보처리기사 실기 개념 14강

- [ ] 정보처리기사 실기  6강

- [ ] 스프링  9-01  ~ 9-05 

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 49~60번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 정렬까지 풀고 문제코드 올리기
https://www.acmicpc.net/step (백준 알고리즘 문제)

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222617223022

**Comment by sohoung** [comment]
AdminUser, OrderDetail api만 남았습니당
