### ISSUE TITLE
[21-01-07] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#82]
- [ ] 정보처리기사 실기 개념 14강

- [ ] 정보처리기사 실기  6강

- [ ] IOS 앱개발 Firebase (3/3)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 1장 49~60번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 입출력과 정렬까지 풀고 문제코드 올리기
https://www.acmicpc.net/step (백준 알고리즘 문제)

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260
