### ISSUE TITLE
[22-01-10] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#86]
- [ ] 정보처리기사 실기 개념 14강

- [ ] 뭐할지 몰라서 수정부탁드림

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 2장 0~12번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 자료구조1 문제와 자료구조1(연습) 풀기
https://code.plus/course/41

200 - 자료구조 1
스택
단어 뒤집기
괄호
스택 수열
에디터
큐
조세퍼스 문제
덱
201 - 자료구조 1 (연습)
단어 뒤집기 2
쇠막대기
오큰수
오등큰수

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222618095187
