### ISSUE TITLE
[22-01-10] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#88]
- [ ] 정보처리기사 실기 개념 15강

- [ ] IOS 앱개발 넷플릭스 확장앱 (1/2)

- [ ] 스위프트 공부한거 블로그 쓰고 주소 댓글 달기

- [ ] 정보처리기사 필기 문제풀이 2장 0~12번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 자료구조1 문제와 자료구조1(연습) 풀기
https://code.plus/course/41

200 - 자료구조 1
스택
단어 뒤집기
괄호
스택 수열
에디터
큐
조세퍼스 문제
덱
201 - 자료구조 1 (연습)
단어 뒤집기 2
쇠막대기
오큰수
오등큰수
