### ISSUE TITLE
[22-01-11] 김민성 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#90]
- [ ] 정보처리기사 실기 개념 17강

- [ ] 자바 공부 수정 부탁

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 2장 13~24번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 이제까지 못한부분이나, 공부해야할 부분 예습,복습하세요.

**Comment by sohoung** [comment]
https://blog.naver.com/sohoung11/222619250681
