### ISSUE TITLE
[22-01-11] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#93]
- [ ] 정보처리기사 실기 개념 17강

- [ ] 자바기초- 자바의 다양항 기능들 (1/3)

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 2장 13~24번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 이제까지 못한부분이나, 공부해야할 부분 예습,복습하세요.
