### ISSUE TITLE
[22-01-12] 김형민 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#97]
- [ ] 정보처리기사 실기 개념 17강

- [ ] 정보처리기사 실기 애플리케이션 테스트 관리 문제풀기

- [ ] 자바기초 - 자바와 자료구조

- [ ] 자바 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 2장 25~36번까지 틀린문제 오답정리

- [ ]  백준 알고리즘 이제까지 못한부분이나, 공부해야할 부분 예습,복습하세요.

**Comment by gudals-kim** [comment]
https://blog.naver.com/kimtuti/222619913862
