### ISSUE TITLE
[21-01-13] 박광현 To-do

### ISSUE THREAD

**Issue by gudals-kim** [gudals-kim/Nobrain-study#98]
- [ ] 정보처리기사 실기 개념 18강

- [ ] 정보처리기사 실기 문제풀이 7강

- [ ] IOS 앱개발 FullScreen 카매라 앱 (2/2)

- [ ] 스위프트 공부한거 블로그에 포스팅 후 댓글

- [ ] 정보처리기사 필기 문제풀이 2장 37~48번까지 틀린문제 오답정리

> **백준 알고리즘 이제까지 못한부분이나, 공부해야할 부분 예습,복습하세요.**

**Comment by park121234** [comment]
https://blog.naver.com/rhkdgus5260
